# Generated by Django 2.2.5 on 2019-09-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeepImage', '0002_auto_20190904_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='original_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='processed_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
