# Generated by Django 2.2.5 on 2019-09-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeepImage', '0003_auto_20190905_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='record',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
