# Generated by Django 2.2.5 on 2019-09-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeepImage', '0004_auto_20190905_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='processed_url',
            new_name='processed_url1',
        ),
        migrations.AddField(
            model_name='record',
            name='processed_url2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
